import { z } from 'zod';
import { getFindings } from '../store/db.js';

const SEVERITIES = ['critical', 'high', 'medium', 'low', 'info'];

export const reportTools = [
  {
    name: 'report_draft',
    description: 'Generate a structured bug bounty report for a finding, ready to paste into HackerOne or Bugcrowd.',
    inputSchema: z.object({
      findingId: z.string().optional().describe('Generate from a stored finding ID'),
      // Or provide details inline
      title: z.string().optional(),
      severity: z.enum(SEVERITIES).optional(),
      type: z.string().optional(),
      url: z.string().optional(),
      description: z.string().optional(),
      impact: z.string().optional(),
      steps: z.array(z.string()).optional(),
    }),
    handler: async ({ findingId, ...inline }) => {
      let data = inline;

      if (findingId) {
        const findings = getFindings();
        const f = findings.find(f => f.id === findingId);
        if (!f) return { success: false, error: `Finding ${findingId} not found` };
        data = { ...f, ...inline };
      }

      const steps = (data.steps || ['[Step 1]', '[Step 2]', '[Step 3]'])
        .map((s, i) => `${i + 1}. ${s}`)
        .join('\n');

      const report = `# ${data.title || '[Title]'}

**Severity:** ${data.severity || '[Severity]'}
**Type:** ${data.type || '[Vulnerability Class]'}
**Endpoint:** ${data.url || '[Affected URL]'}

## Summary

${data.description || '[Describe what you found and why it is a vulnerability.]'}

## Steps to Reproduce

${steps}

## Impact

${data.impact || '[Describe the business/security impact if exploited.]'}

## Remediation

[Suggest a fix — e.g., validate input server-side, enforce authorization checks, add Content-Security-Policy header.]

---
*Report generated by bugbounty-mcp*`;

      return { success: true, report };
    },
  },
  {
    name: 'report_summary',
    description: 'Generate a summary of all findings for a program — useful for tracking progress.',
    inputSchema: z.object({
      program: z.string().describe('Program name'),
    }),
    handler: async ({ program }) => {
      const findings = getFindings({ program });
      if (!findings.length) return { success: true, summary: `No findings logged for ${program}.` };

      const bySeverity = SEVERITIES.reduce((acc, s) => {
        acc[s] = findings.filter(f => f.severity === s).length;
        return acc;
      }, {});

      const byStatus = findings.reduce((acc, f) => {
        acc[f.status] = (acc[f.status] || 0) + 1;
        return acc;
      }, {});

      const totalBounty = findings.reduce((sum, f) => sum + (f.bounty || 0), 0);

      const summary = `# ${program} — Finding Summary

## Severity Breakdown
${SEVERITIES.map(s => `- **${s}**: ${bySeverity[s]}`).join('\n')}

## Status Breakdown
${Object.entries(byStatus).map(([k, v]) => `- **${k}**: ${v}`).join('\n')}

## Total Bounty Earned: $${totalBounty}

## Findings
${findings.map(f => `- [${f.severity.toUpperCase()}] ${f.title} (${f.status}) — ${f.url}`).join('\n')}`;

      return { success: true, summary };
    },
  },
];
